---
title: "R Notebook"
output: html_notebook
editor_options: 
  markdown: 
    wrap: 72
---

```{markdown}

title: "Brain stroke"


##Goal of collecting this Dataset

Our goal of collecting a dataset about brain stroke is to gather
relevant and accurate information about this medical condition by
gathering information about the patients health history,age and
gender.This data will help enhancing patient care so that researchers
and healthcare professionals can gain knowledge of the risk factors
,causes, age rating of patients and symptoms associated with brain
stroke.

Classification goal:

We want to classify the patients to be able to accurately predict
whether a patient will have a stroke or not based on age, medical
history and gender. Using this classification we can help in early
identification and prevention of strokes ,this would help us for a
better patient care.

The Problem statement:
To use data mining techniques to help researchers for early detection, risk assessment, and improved understanding of brain strokes, explore the given dataset on brain stroke and develop a predictive model that can identify the key risk factors associated with stroke. Specifically, the project aims to:

1. Perform exploratory data analysis to gain insights into the distribution and characteristics of the variables in the dataset.
2. Identify the most significant variables and their relationships with stroke occurrence using statistical analysis and data visualization techniques.
3. Preprocess the dataset by handling missing values, outliers, and categorical variables, ensuring data quality and consistency.
4. Select appropriate data mining techniques, such as classification algorithms, to build a predictive model for stroke risk assessment.


##The source

The dataset was sourced from kaggle website The link:
[here](https://www.kaggle.com/datasets/jillanisofttech/brain-stroke-dataset).

##General information

Number of Attributes: 11, Number of Objects: 4982, Class label: brain
stroke status 1 if the patient had a stroke 0 if not.

1)  gender: "Male", "Female"

2)  age: age of the patient

3)  hypertension: 0 if the patient doesn't have hypertension, 1 if the
    patient has hypertension

4)  heart disease: 0 if the patient doesn't have any heart diseases, 1
    if the patient has a heart disease

5)  Ever-married: "No" or "Yes"

6)  work type: "children", "Govt_job", "Never worked", "Private" or
    "Self-employed"

7)  Residence type: "Rural" or "Urban"

8)  avg glucose level: average glucose level in blood

9)  BMI: body mass index

10) smoking_status: "formerly smoked", "never smoked", "smokes" or
    "Unknown"

11) stroke: 1 if the patient had a stroke or 0 if not

    | attribute name    | data type | description                                      | possible values                                                      |
    |-----------------|-----------------|---------------------|-----------------|
    | gender            | string    | Gender of the patient (e.g., Male, Female).      | Male, Female                                                         |
    | Age               | decimal   | Patient's age in years at the time of assessment | 0.08 to 82                                                           |
    | hypertension      | integer   | if the patient has hypertension                  | 0 or 1                                                               |
    | heart disease     | integer   | if the patient has heart disease                 | 0 or 1                                                               |
    | Residence type    | string    | the residence type of the patient                | "Rural" or "Urban"                                                   |
    | Ever-married      | string    | if the patient has ever married or not           | "No" or "Yes"                                                        |
    | work type         | string    | the work type of the patient                     | "children", "Govt_job", "Never worked", "Private" or "Self-employed" |
    | avg glucose level | decimal   | average glucose level in blood                   | 55.1 - 272                                                           |
    | BMI               | decimal   | Body Mass Index (BMI) of the patient.            | 14 - 48.9                                                            |
    | smoking status    | string    | the smoking status of the patient                | "formerly smoked", "never smoked", "smokes" or "Unknown"             |
    | stroke            | integer   | if the patient had a stroke or not               | 0 or 1   |

```

 
 
 
 
 
#Load dataset
library(readr)
brain_stroke <- read_csv("brain_stroke.csv")
View(brain_stroke)



#Load necessary libraries

library(dplyr)
library(ggplot2)
library(outliers)


#number of rows
 nrow(brain_stroke)

#number of columns
 ncol(brain_stroke)


#sample of raw dataset
 head(brain_stroke,n=10)
 

#missing values
is.na(brain_stroke)
sum(is.na(brain_stroke))
#The output is 'false,' which suggests that there are no missing elements in our dataset


#statistical summaries
summary(brain_stroke$age)
summary(brain_stroke$avg_glucose_level)
summary(brain_stroke$bmi)



var(brain_stroke$age)
var(brain_stroke$avg_glucose_level)
var(brain_stroke$bmi)


#boxplots 
 
#boxplot of age 
# Create a boxplot to visualize the distribution of ages in our dataset, it includes the median, quartiles, and potential outliers of the age variable.

 boxplot.stats(brain_stroke$age)$out
 boxplot(brain_stroke$age)

#boxplot of avg_glucose_level
# Create a boxplot to visualize the distribution of avg_glucose_level in our dataset, it includes the median, quartiles, and potential outliers of the avg_glucose_level variable.
 boxplot.stats(brain_stroke$avg_glucose_level)$out
 boxplot(brain_stroke$avg_glucose_level)

#boxplot of bmi 
# Create a boxplot to visualize the distribution of bmi in our dataset, it includes the median, quartiles, and potential outliers of the bmi variable.
 boxplot.stats(brain_stroke$bmi)$out
 boxplot(brain_stroke$bmi)


#histogram

# Shows Distribution of ages


hist(brain_stroke$age, col = "purple", main = "Age Distribution", xlab = "Age")

#We notice from this histogram that the majority of people in this dataset are between the  ages of 40 to 60

#Scatter plot

# Shows the relationship between two attributes: "average glucose level" (on the x-axis) and "BMI" (Body Mass Index, on the y-axis)


ggplot(brain_stroke, aes(x = avg_glucose_level, y = bmi)) +
  geom_point() +
  labs(title = "Scatter Plot: BMI & average glucose level")
 
cor(brain_stroke$avg_glucose_level, brain_stroke$bmi)

#[1] 0.1863482
#Based on the scatter plot and the correlation number We noticed that the correlation between the two attributes is very weak because the correlation is between 0 and 0.199.

#pie charts

# Shows Distribution of Residence Types


tab <- brain_stroke$Residence_type %>% table()
precentages <- tab %>% prop.table() %>% round(3) * 100 
txt <- paste0(names(tab), '\n', precentages, '%') # text on chart
pie(tab, labels=txt)

#We notice from this pie chart that the majority of people in this dataset live in urban residence

#Bar Plots

# 1 - Shows the disturbution of work type 

  ggplot(brain_stroke, aes(x = work_type, fill = work_type)) +
  geom_bar(color = "black") +
  labs(title = "Bar Plot: Distribution of Work Type") +
  scale_fill_discrete() 
  


#We notice from this bar plot that the majority of people in this dataset work for a private organization.

#After encoding, 'Children' will be number 1, 'Govt_job' will be number 2, 'Private' will be number 3, and 'Self-employed' is number 4.
  
  
# 2 - The resulting plot visually shows the distribution of heart disease cases and their association with brain stroke.

library(ggplot2)
library(dplyr)
  percentages <- brain_stroke %>%
  group_by(heart_disease, stroke) %>%
  summarize(count = n()) %>%
  mutate(percentage = (count / sum(count)) * 100)

ggplot(brain_stroke, aes(x = factor(heart_disease), fill = stroke)) +
  geom_bar() +
  geom_text(data = percentages, aes(label = paste0(round(percentage, 1), "%"), y = count), 
            position = position_stack(vjust = 0.5)) +
  labs(x = "Heart Disease", y = "Count", fill = "Stroke") +
  scale_x_discrete(labels = c("No Heart Disease", "Heart Disease")) +
  ggtitle("Barplot of Heart Disease and Stroke") +
  theme_minimal()
  

#The perecentage at the top of the column shows the percentage of having a brain stroke 
#We notice from this bar plot that people with heart disease have a higher risk of experiencing a brain stroke

# 3 - The resulting plot visually shows the distribution of hypertension cases and their association with brain stroke.

 percentages <- brain_stroke %>%
  group_by(hypertension, stroke) %>%
  summarize(count = n()) %>%
  mutate(percentage = (count / sum(count)) * 100)

ggplot(brain_stroke, aes(x = factor(hypertension), fill = stroke)) +
  geom_bar() +
  geom_text(data = percentages, aes(label = paste0(round(percentage, 1), "%"), y = count), 
            position = position_stack(vjust = 0.5)) +
  labs(x = "Hypertension", y = "Count", fill = "Stroke") +
  ggtitle("Barplot of Hypertension and Stroke") +
  theme_minimal()
  
#The perecentage at the top of the column shows the percentage of having a brain stroke 
#We notice from this bar plot that people with hypertension have a higher risk of experiencing a brain stroke.
  
# 4 - bar blot that helps visualize if there is any association between smoking status and the likelihood of experiencing a stroke.


percentages <- brain_stroke %>%
  group_by(smoking_status, stroke) %>%
  summarize(count = n()) %>%
  mutate(percentage = (count / sum(count)) * 100)

ggplot(brain_stroke, aes(x = smoking_status, fill = stroke)) +
  geom_bar() +
  geom_text(data = percentages, aes(label = paste0(round(percentage, 1), "%"), y = count), 
            position = position_stack(vjust = 0.5)) +
  labs(x = "Smoking Status", y = "Count", fill = "Stroke") +
  ggtitle("Distribution of Smoking Status in Relation to Stroke") +
  theme_minimal()

#The perecentage at the top of the column shows the percentage of having a brain stroke  
#We notice from this bar plot that people who formerly smoked and smokes have a higher risk of experiencing a brain stroke.



#outliers 


Outavg_glucose_level = outlier(brain_stroke$avg_glucose_level, logical =TRUE) 
sum(Outavg_glucose_level) 
Find_outlier = which(Outavg_glucose_level ==TRUE, arr.ind = TRUE) 
Outavg_glucose_level 
Find_outlier

Outbmi = outlier(brain_stroke$bmi, logical =TRUE) 
sum(Outbmi) 
Find_outlier = which(Outbmi ==TRUE, arr.ind = TRUE) 
Outbmi 
Find_outlier

Outage = outlier(brain_stroke$age, logical =TRUE) 
sum(Outage) 
Find_outlier = which(Outage ==TRUE, arr.ind = TRUE) 
Outage 
Find_outlier
#By removing outliers, we improve the overall quality and accuracy of the dataset. This helps ensure that the data reflects the true relationships.


#normlization 
normalize <- function(x) {return ((x - min(x)) / (max(x) - min(x)))}
dataWithoutNormalization <- brain_stroke
brain_stroke$bmi<-normalize(dataWithoutNormalization$bmi) 
brain_stroke$age<-normalize(dataWithoutNormalization$age) 
brain_stroke$avg_glucose_level<-normalize(dataWithoutNormalization$age) 
print(brain_stroke)

#discretization
#we do not need feature discretization because the data is already well-preprocessed.

#feature selection - correlation analysis (numric)
cor(brain_stroke$age, brain_stroke$stroke) 
cor(brain_stroke$bmi, brain_stroke$stroke) 
cor(brain_stroke$hypertension, brain_stroke$stroke) 
cor(brain_stroke$heart_disease, brain_stroke$stroke)
cor(brain_stroke$avg_glucose_level, brain_stroke$stroke)

#There’s a weak correlations between numerical attributes (typically below 0.3) . This implies that feature selection isn't necessary.

#feature selection - chi square (cateorigal) 

chi_squared_result <- chisq.test(table(brain_stroke$gender, brain_stroke$stroke))
print(chi_squared_result)

chi_squared_result <- chisq.test(table(brain_stroke$work_type, brain_stroke$stroke))
print(chi_squared_result)

chi_squared_result <- chisq.test(table(brain_stroke$Residence_type, brain_stroke$stroke))
print(chi_squared_result)

chi_squared_result <- chisq.test(table(brain_stroke$smoking_status, brain_stroke$stroke))
print(chi_squared_result)

chi_squared_result <- chisq.test(table(brain_stroke$ever_married, brain_stroke$stroke))
print(chi_squared_result)

#After each test, the result is used to display the chi-squared test result, including the chi-squared statistic, degrees of freedom, by comparing chi-square value with the DF in  the probability level table, it showed that the attributs "work_type", "smoking_status", "ever_married" have a greater chi square value than DF value.

#delete work_type,ever_married,smoking_status coloumns
data <-data[,!names(data) %in% c("work_type", "smoking_status", "ever_married")]
head(data)